title: Christine Harris
# logo: "/images/logo.png?raw=true"
logo: "/images/Portfolio_Portrait_Smaller_3.PNG"
description: >
  Soon-to-be graduate of the Statistics MSc program at The London School of Economics (expected December 2020) with a strong interest in data science and machine learning.     
  <br><br>
  <a href="https://www.linkedin.com/in/christinewharris/">View My LinkedIn Profile</a> 
theme: jekyll-theme-minimal
