title: Christine Harris
# logo: "/images/logo.png?raw=true"
description: >
  Soon-to-be graduate of the Statistics MSc program at The London School of Economics (expected December 2020). Prior to graduate school, I worked professionally for three years as a Research Analyst for The Brattle Group. Post-graduation, I am looking to transition into the field of data science.     
  <br><br>
  This portfolio is a compilation of notebooks, reports, and analyses that I have created over the past few years for either graduate/undergraduate courses or personal development.
  <br><br>
  <a href="https://www.linkedin.com/in/christinewharris/">View My LinkedIn Profile</a> 
theme: jekyll-theme-minimal
