title: Christine Harris
# logo: "/images/logo.png?raw=true"
description: >
  Soon-to-be graduate 
  <br><br>
  This portfolio is a compilation of notebooks, reports, and analyses that I have created over the past few years for either graduate/undergraduate courses or for personal development.
  <br><br>
  <a href="https://www.linkedin.com/in/christinewharris/">View My LinkedIn Profile</a> 
theme: jekyll-theme-minimal
