theme: jekyll-theme-minimal

# --- Required options --- #

# Name of website
title: Christine Harris

# Website description
description: Data Scientist

# Your name to show in the footer
author: Christine Harris

