title: Christine Harris
# logo: "/images/logo.png?raw=true"
description: >
  First description 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/christinewharris/">View My LinkedIn Profile</a> 
theme: jekyll-theme-minimal
