# theme: jekyll-theme-minimal
theme: minimal-mistakes-jekyll

minimal_mistakes_skin: "air"

# --- Required options --- #

# Name of website
title: Christine Harris

# Website description
description: Data Scientist
