title: Christine Harris
# logo: "/images/logo.png?raw=true"
logo: "/images/Portrait.JPG"
description: >
  Soon-to-be graduate of the Statistics MSc program at The London School of Economics (expected December 2020) who is seeking employment as a full-time data scientist.     
  <br><br>
  This portfolio is a compilation of notebooks, reports, and analyses that I have created over the past few years for either graduate/undergraduate courses or personal development.
  <br><br>
  <a href="https://www.linkedin.com/in/christinewharris/">View My LinkedIn Profile</a> 
theme: jekyll-theme-minimal
